### ISSUE TITLE
build instructions slightly wrong?

### ISSUE THREAD

**Issue by tommythorn** [riscv/riscv-linux#1]
[Reposted from an  ucb-bar / riscv-tools issue]

Thank you so much! It's working brilliantly.

I had to make a few modifications to get it to work: first arch wants to be inside linux-3.4.76 so I did

```
mkdir linux-3.4.76 && mv arch linux-3.4.76
```

before the curl step. Also, building riscv-gcc with make linux fails for me, but the riscv-tools works great, so I instead just edited arch/riscv/configs/riscv_defconfig:CONFIG_CROSS_COMPILE to point to riscv- instead of riscv-linux-

**Comment by terpstra** [comment]
This was fixed years ago.
