### ISSUE TITLE
upstream arch/riscv/configs/defconfig is empty

### ISSUE THREAD

**Issue by davidlt** [riscv/riscv-linux#118]
Based on https://github.com/riscv/riscv-qemu/pull/79 there are suggestions for some new default CONFIG options for `arch/riscv/configs/defconfig`. 

When I looked into the v4.15-rc3 for the current defaults, I found none (apart what you get from Kconfig): https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/arch/riscv/configs/defconfig?h=v4.15-rc3

While freedom-u-sdk has the following: https://github.com/sifive/freedom-u-sdk/blob/master/conf/linux_defconfig which probably is a good starting point, plus things from the mentioned pull request later on.

Other beneficial default things could be NFS, ext* stuff, namespaces, cgroups (basically thing to allow containers), etc. I could try to study arm64 defconfig to see what people added and why. Otherwise the kernel is very bare.

**Comment by palmer-dabbelt** [comment]
It's full of stuff now :)
