### ISSUE TITLE
Stopping lo interface Oops

### ISSUE THREAD

**Issue by dalegr** [riscv/riscv-linux#146]
Hi!

Kernel 4.18
I had to implement sifive drivers from kernel 4.15 to this kernel because otherwise it do not switch bootconsole.

Now I have a strange issue when loading a kernel 4.18 natively on risc v.
One can find log down below.
Could somebody help me with it please?

INIT: Switching to runlevel: 2
INIT: Sending processes the TERM signal
[   33.046158] Stopping udevd service:               [DONE]
[   33.350120] Stopping lo interface: [   33.350000] Oops [#1]
[   33.350000] CPU: 3 PID: 73 Comm: kworker/3:1 Tainted: G        W         4.18.0-rc6 #20
[   33.360000] Workqueue: rcu_gp wait_rcu_exp_gp
[   33.360000] sepc: ffffffe000866da0 ra : ffffffe0004b8878 sp : ffffffe1f67abca0
[   33.370000]  gp : ffffffe0009f70b8 tp : ffffffe1f6654400 t0 : 0000000000000000
[   33.380000]  t1 : 0000000000006000 t2 : 0000000000000000 s0 : ffffffe1f67abcb0
[   33.390000]  s1 : ffffffe0004a5900 a0 : f597862680826161 a1 : 000000007fffffff
[   33.390000]  a2 : ffffffe0009b0f08 a3 : 0000000000000001 a4 : 0000000000000001
[   33.400000]  a5 : 000000007fffffff a6 : 8080808080808080 a7 : ffffffe1f7bd0368
[   33.410000]  s2 : ffffffe0009b0f08 s3 : ffffffe00049e0b0 s4 : 0000000000000000
[   33.410000]  s5 : 0000000000000000 s6 : ffffffe000aa3698 s7 : ffffffe0009f75f0
[   33.420000]  s8 : ffffffe00049e0b0 s9 : 0000000000000088 s10: f597862680826161
[   33.430000]  s11: ffffffe1f7a07000 t3 : ffffffe0009a17c0 t4 : ffffffe0009a17c8
[   33.440000]  t5 : 0000000000000007 t6 : 0000000000000006
[   33.440000] sstatus: 0000000200000100 sbadaddr: 0000002680826161 scause: 000000000000000d
[   33.450000] ---[ end trace 5cda2dd0e1ac83e3 ]---

**Comment by palmer-dabbelt** [comment]
You should be able to get a boot console if you have `CONFIG_HVC_RISCV_SBI=y` in your `.config`.

As to the RCU bug: I'd guess it's an error with your backports, as I don't see that on my end.  There's currently a lot of flux in our CPU up/down support as well as our timer interface, so it's not a great time to try to backport everything.  Your best bet is to try the "riscv-linux-4.18" branch, which is based on Linus' 4.18 but has all the backports we expect to be clean.  I'll be adding patches to that branch as we get the kernel in better shape, but it'll take a while for all our drivers to filter through the system.

**Comment by dalegr** [comment]
Thank you!
