### ISSUE TITLE
unknown architecture riscv.

### ISSUE THREAD

**Issue by akashgj** [riscv/riscv-linux#147]
I cloned Linux v4.12 and tried to cross compile using riscv-unknown-linux-gnu-gcc. It is showing error like unknown architecture riscv. Further checked 'arch' directory of kernel and unable to find 'riscv' directory inside it. Please someone help to get Linux v4.12 with riscv architectural support.

**Comment by palmer-dabbelt** [comment]
We didn't get the RISC-V kernel port upstream until 4.15.  Backporting our patches to 4.12 would be a big task, so I'm going to close this as a WONTFIX on my end.  Your best bet is probably to use a newer kernel, I'd suggest the `riscv-linux-4.18` backports branch for now.
