### ISSUE TITLE
GPIO & PWM spec for Unleashed

### ISSUE THREAD

**Issue by atishp04** [riscv/riscv-linux#148]
I am planning to cleanup linux GPIO & PWM driver for Unleashed board. 
Can I access the specs for these devices ?

@palmer-dabbelt @terpstra

**Comment by terpstra** [comment]
https://www.sifive.com/documentation/chips/freedom-u540-c000-manual/

Chapters 14 and 17

**Comment by atishp04** [comment]
Thanks @terpstra .
