### ISSUE TITLE
[question ]fatal error in the step of Configuring the Linux Kernel:

### ISSUE THREAD

**Issue by c13163** [riscv/riscv-linux#45]
the fatal error problem shows as below
/////////////////////////////////////////////////////
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CC      scripts/mod/devicetable-offsets.s
In file included from include/linux/compiler.h:54:0,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from /home/genji/riscvCPU/linux-3.14.33/include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from include/linux/mod_devicetable.h:11,
                 from scripts/mod/devicetable-offsets.c:2:
include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
compilation terminated.
scripts/Makefile.build:204: recipe for target 'scripts/mod/devicetable-offsets.s' failed
make[2]: *** [scripts/mod/devicetable-offsets.s] Error 1
scripts/Makefile.build:455: recipe for target 'scripts/mod' failed
make[1]: *** [scripts/mod] Error 2
Makefile:527: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: *** Waiting for unfinished jobs....
///////////////////////////////////////////////

  
https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.14.33.tar.xz | tar     include/linux  does not provide compiler-gcc6.h    I don't know how to do the following jobs.     Help me please,thank you very much!

**Comment by a0u** [comment]
You should be using the 4.6 series with the master branch - take a look at the README.
