### ISSUE TITLE
Cherry-pick some commits from sifive/riscv-linux:sifive

### ISSUE THREAD

**Issue by terpstra** [riscv/riscv-linux#46]
Although using the config string for linux boot seems to not be popular, there are nevertheless some commits in the sifive linux kernel branch that should probably be moved to the main linux repo.

Specifically:
* The commit which makes VTs work via dummy terminal (needed for X/fb/etc)
* The fix that prevents kernel panic by pressing a key during early_printk
* The patch that adds DMA by marking risc-v as coherent (needed by PCIe)
* The patch that adds PCI capability via ECAM, since riscv has no x86 IO space.

The device drivers for PLIC, GPIO, and Xilinx-PCIe probably can't be merged until we have a solution to provide DTS from the boot loader. But there is no reason not to merge as much as possible into one repository (this one).

**Comment by a0u** [comment]
See PR #47.

The commit `sbi-con: do not panic on keypresses during boot` was omitted since this is fundamentally an issue with IRQ handler registration and needs a different solution.
