### ISSUE TITLE
OS support for virtual memory

### ISSUE THREAD

**Issue by susi655** [riscv/riscv-linux#50]
What kind of support is provided by RISCV Linux OS for virtual memory?

For example,
Is page walk managed by OS?
What about TLB filling? etc.

**Comment by sorear** [comment]
Linux uses the standard page table described in the privileged spec.  How TLBs work is a question for your chip vendor.

**Comment by susi655** [comment]
So TLB filling is done by hardware. Is it?

**Comment by sorear** [comment]
It can be done by hardware or software.  It is _not_ done by Linux.

**Comment by susi655** [comment]
Few doubts regarding Page table
   Is it optional to implement hardware page walker?
   If it is can be done by software, up to what extent OS will do?
   Means decision of which page to replace will done by OS?
Is OS looking for multi-level paging?

**Comment by sorear** [comment]
The bug tracker is not a forum and this isn't even a related repository.

Page table walker is not in the OS.  If it's software, it's non-OS software (e.g. M-mode trap handled in a M-mode monitor program that runs above Linux).  Why do you keep asking?  What are you trying to achieve?

*As far as any OS knows*, page tables are walked automatically.

**Comment by palmer-dabbelt** [comment]
I'm closing this: like @sorear said this isn't the right place to ask this question.  isa-dev@groups.riscv.org might be a better place to do it.
