### ISSUE TITLE
kernel/sbi.S

### ISSUE THREAD

**Issue by noamc** [riscv/riscv-linux#70]
What is the propose of this file? where are values coming from?
I can't see it in riscv-next branch, instead I see OF use of some device tree, but I can't see the DTS file

**Comment by palmer-dabbelt** [comment]
This is the old SBI implementation, we've changed the SBI to use ecalls and traps.  The old SBI implementation uses a page of trampolines, which the idea being that machine-mode implementations that had very fast implementations of the SBI calls could avoid the cost of a m-mode trap and implement them inline.

**Comment by palmer-dabbelt** [comment]
This file doesn't even exist any more.
