### ISSUE TITLE
Failed to boot linux kernel

### ISSUE THREAD

**Issue by bensenq** [riscv/riscv-linux#83]
Does spike of the  current version  support boot linux kernel?

I've built bbl with linux kernel as its payload, and then run `spike bbl` , but no kernel or user message show up, why? 

Branches:

- riscv-fesrv: master
- riscv-isa-sim: master
- riscv-poky: master
- riscv-linux: riscv-next

**Comment by bensenq** [comment]
By the way,  `spike pk hello` gives right message.

**Comment by bensenq** [comment]
The spike is in the infinite loop:

```
core   0: exception trap_instruction_access_fault, epc 0x0000000000000000
core   0:           badaddr 0x0000000000000000
```

I think it's a version mismatch.

**Comment by palmer-dabbelt** [comment]
There should be matching versions in github.com/sifive/freedom-u-sdk on the "new" branch, which we'll merge when we have a handful of issues sorted out.  I'm going to close this.
