### ISSUE TITLE
RTOS support on RISCV

### ISSUE THREAD

**Issue by kelayamatoz** [riscv/riscv-linux#84]
Dear RISCV Team,

I am wondering that if there's an Real time OS linux that would be compatible with RISCV rocket-chip core? If so, could you point me to the right direction? 

Thanks!

**Comment by palmer-dabbelt** [comment]
We have ports of Zephyr and FreeRTOS floating around.  The sw-dev mailing is probably a better place to ask about this, I'm closing the issue.
