### ISSUE TITLE
fopen return error #38

### ISSUE THREAD

**Issue by jimmyzzzzzz** [riscv/riscv-linux#86]
I have put a binary that contains fopen() function in the root of disk image. But it generates errno #38 when fopen() function is called and file pointer is NULL. Some other applets like cat and redirection to output file works fine in riscv linux which means that files can be read and written. Is there anything I missed in configuration or anything else?

Thank you.

**Comment by palmer-dabbelt** [comment]
If this still manifests with the latest versions tagged in freedom-u-sdk then feel free to re-open the issue.
