### ISSUE TITLE
No /Documentation/riscv/booting.txt - plan to implement spin-table?

### ISSUE THREAD

**Issue by DSHorner** [riscv/riscv-linux#90]
Indeed, no /Documentation/riscv directory.

As Mark Rutland recommended, is there a plan to implement a spin-table to enable harts?

The decision and possibly some of the discussion on this can go into /Documentation/riscv/booting.txt

**Comment by palmer-dabbelt** [comment]
We're looking into a good way to do this right now, but it might take a while because I've got to sort out some toolchain issues first.

**Comment by palmer-dabbelt** [comment]
I'm closing this in favor of a patch.  https://github.com/riscv/riscv-linux/pull/108
