### ISSUE TITLE
Infinite loop in relocate

### ISSUE THREAD

**Issue by francescodg** [riscv/riscv-linux#92]
We are running the kernel on FPGA with Rocket Chip core.
When relocate returns with _ra_ as a virtual address, it raises a trap that eventually ends in this loop:
```
	/* Set trap vector to spin forever to help debug */
	la a0, .Lsecondary_park
	csrw stvec, a0
```
Is this the intended behaviour? Does it mean that address translation is not performed correctly?

**Comment by palmer-dabbelt** [comment]
That trap loop is there to help catch bugs in early boot, so something's broken.  If this still manifests with the latest freedom and freedom-u-sdk, then feel free to re-open the issue.
