### ISSUE TITLE
Running "spike bbl" command freezing  in the current build

### ISSUE THREAD

**Issue by vinod1993** [riscv/riscv-linux#94]
Hello,
       I built the complete Linux environment by following the steps provided in this as well as the ones given in riscv-tools repository. I did the following steps.
       1. Built the busybox utility with all the suggested menu-configurations. There were two ways of getting the initramfs.txt and inittab files (one in riscv-tools and the other here). I used the steps from this repository. 
        2. Successfully built the linux kernel image (vmlinux) and bbl (after recompiling both riscv-linux and riscv-pk).
However, When I run the command spike bbl, it just freezes instead of the debug printk's on the screen and when you try to come out (forcefully - upon ctrl+C), Spike goes to debug mode. There also seems to be a trap instruction access fault when you try to execute it in debug mode.
        3. I have another build where I followed the same steps, on a previous version of the riscv-tools  which seems to work fine, where the bootup process goes till the ash terminal invocation. Please help.

**Comment by palmer-dabbelt** [comment]
This is usually a version mismatch between Spike and Linux.  Can you try the versions tagged on the "new" branch of github.com/sifive/freedom-u-sdk?

**Comment by vinod1993** [comment]
Thanks for the reply Palmer. I will try and let you know.

**Comment by palmer-dabbelt** [comment]
There's a coherent set of versions tagged in freedom-u-sdk, if that doesn't work then feel free to re-open the bug.

**Comment by edcote** [comment]
this is a failure in my CI system, any tips on how one would root cause the issue? or, at the very least, get a trace, error msg, that I can use for triage?

**Comment by palmer-dabbelt** [comment]
Well, you've got the illegal instruction right there in epc.  You should be able to figure out what function it's in by looking at your Linux binary, if you can upload an "riscv*-objdump -d vmlinux" then I can take a look.
